### ISSUE TITLE
I hope that all the tables are added to the configuration rules by default.

### ISSUE THREAD

**Issue by gongandkai** [sharding-sphere/sharding-sphere#1237] opened 2018-09-06 01:35 UTC
###Which version of Sharding-Sphere do you using?

3.0.0.M2

###Which project do you using? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC  

###Expected behavior

My database has nearly 100 tables, whether all of them have to be configured once.

I hope that all the tables are added to the configuration rules by default.

Expected add spring  configuration 
eg.

```
sharding.jdbc.datasource.allTalbesAdd2Rule=true
```

###Actual behavior

need set defaultDataSource （getDefaultDataSourceName）   

```java
 public TableRule getTableRuleByActualTableName(String actualTableName) {
        Optional<TableRule> tableRule = this.tryFindTableRuleByActualTable(actualTableName.toLowerCase());
        if (tableRule.isPresent()) {
            return (TableRule)tableRule.get();
        } else if (!Strings.isNullOrEmpty(this.shardingDataSourceNames.getDefaultDataSourceName())) {
            return this.createTableRuleWithDefaultDataSource(actualTableName.toLowerCase());
        } else {
            throw new ShardingConfigurationException("Cannot find table rule and default data source with actual table: '%s'", new Object[]{actualTableName});
        }
  }
```

 Actual ,there hasn't default by business and design

**Comment by terrymanu** [comment] 2018-09-06 01:51
Thank your suggestion, we will consider about that.

**Comment by terrymanu** [comment] 2018-09-06 01:55
But I need to confirm the precondition: 

How does Sharding-Sphere know the actual-data-source if configuration absent?

**Comment by gongandkai** [comment] 2018-09-06 02:33
before :
```
@RequiredArgsConstructor
public final class StandardRoutingEngine implements RoutingEngine {
    
    private final ShardingRule shardingRule;
    
    private final String logicTableName;
    
    private final ShardingConditions shardingConditions;
    
    @Override
    public RoutingResult route() {
        TableRule tableRule = shardingRule.getTableRuleByLogicTableName(logicTableName);
```




after
 add param shardingConditions
`   TableRule tableRule = shardingRule.getTableRuleByLogicTableName(logicTableName,shardingConditions);`

becase shardingConditions has  gDataSourceNames

using
```

  public TableRule getTableRuleByLogicTableName(final String logicTableName,ShardingConditions shardingConditions) {
        Optional<TableRule> tableRule = tryFindTableRuleByLogicTable(logicTableName.toLowerCase());
        if (tableRule.isPresent()) {
            return tableRule.get();
        }
        //add
        if ( shardingRuleConfig.allTalbesAdd2Rule()) {
            if(shardingConditions.getShardingConditions  == shardingDataSourceNames.getDataSourceNames().get(i)){
                TableRuleConfiguration tableRuleConfig = new TableRuleConfiguration();
                tableRuleConfig.setLogicTable(logicTableName);
                tableRuleConfig.setActualDataNodes(shardingDataSourceNames.getDataSourceNames().get(i)+ "." + logicTableName);
                return new TableRule(tableRuleConfig, new ShardingDataSourceNames(shardingRuleConfig, Collections.singletonList(shardingDataSourceNames.getDefaultDataSourceName())));

            }
         `}`

        if (!Strings.isNullOrEmpty(shardingDataSourceNames.getDefaultDataSourceName())) {
            return createTableRuleWithDefaultDataSource(logicTableName);
        }
        throw new ShardingConfigurationException("Cannot find table rule and default data source with logic table: '%s'", logicTableName);
    }

```

**Comment by terrymanu** [comment] 2018-09-06 02:50
What I mean is sharding rule configuration need to configure actual-data-nodes, it just like:

```
ds_0.tbl_0, ds_0.tbl_1, ds_1.tbl_0,ds_1.tbl_1
```

If config it automatically, how Sharding-Sphere to know the data source name is `ds_0` or `ds1`?

**Comment by terrymanu** [comment] 2018-09-06 02:51
We need discuss config first, just ignore how to implement it. For end-users, they don't care about how to implement, but care about how to config.

**Comment by gongandkai** [comment] 2018-09-06 05:28
Is a problem， sorry about that I forget my project just has sharding database not has shradingtable

**Comment by terrymanu** [comment] 2018-09-06 05:53
The problem is not all data sources are same. Maybe data source A and B config by table rule A, and data source C config by table rule B. 

We can not assume all data sources must config for every tables.

So I just close this issue for now

**Closed by terrymanu** 2018-09-06 05:53 UTC
Labels: discussion
