### ISSUE TITLE
I want to support filtering non-shared tables

### ISSUE THREAD

**Issue by 799983050** [sharding-sphere/sharding-sphere#1609] opened 2018-12-13 02:11 UTC
I want to support filtering non-shared tables
This way, non-shared tables do not receive SQL restrictions from ss

**Comment by terrymanu** [comment] 2018-12-13 02:31
If not parsing SQL, how to ShardingSphere know this SQL is sharding or non-sharding?

**Comment by 799983050** [comment] 2018-12-13 06:41
For example, my sharding strategy is single-db multi-table。There are now two tables, order and user，order tables is configured in  application-sharding-tables.xml sharding，The user table has no configuration。 So I am executing select * from user where id = XXX, can I judge whether the user table has no Shared configuration, skip ss parsing and go directly to the target library to execute SQL。
        Multiple db and multiple tables can optionally configure a default execution library to execute SQL for non-sharding tables.Because the non-sharding table will only be in one library

**Comment by terrymanu** [comment] 2018-12-13 15:05
If not parsing SQL, how to ShardingSphere know table `user` is not configure in sharding rule?

**Comment by 799983050** [comment] 2018-12-14 01:57
parsing SQL,Resolve the table name first, and if the table is not in the configuration, jump out of the ss other steps

**Comment by terrymanu** [comment] 2018-12-14 02:10
If ShardingSphere can parse table name from subquery, why ShardingSphere don't support subquery directly?

**Comment by terrymanu** [comment] 2018-12-14 02:12
ShardingSphere parse for one SQL only one time, if try to parse table one time, and then parse other segment, how do you consider about performance?

**Comment by terrymanu** [comment] 2018-12-17 14:58
If it is a new problem, please create a new issue. Can I close this issue now?

**Comment by terrymanu** [comment] 2018-12-24 15:09
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Closed by terrymanu** 2018-12-24 15:09 UTC
Labels: discussion, need feedback
