### ISSUE TITLE
sharding-proxy docker： concat 3 times，return to the fragment field normally.

### ISSUE THREAD

**Issue by y42775jp** [sharding-sphere/sharding-sphere#1221] opened 2018-09-02 09:13 UTC
![image](https://user-images.githubusercontent.com/3135203/44954364-6d4e9880-aed3-11e8-8210-67d25b3d97e9.png)

navicat:  SELECT CONCAT(eid,eid,eid) from t_enterprise;  
return eid

**Comment by ma-xiao-guang-64** [comment] 2018-09-03 01:42
l test this, but no problem
![tim 20180903094023](https://user-images.githubusercontent.com/6637227/44963482-68cec200-af5d-11e8-92e3-6d7f8002d7d2.png)
please provider your proxy version and other useful detail

**Comment by terrymanu** [comment] 2018-09-11 16:40
No feedback anymore, not enough information, cannot reproduce, I just close it and put it as invalid

**Closed by terrymanu** 2018-09-11 16:40 UTC
Labels: need feedback
