### ISSUE TITLE
DeadlockLoserDataAccessException

### ISSUE THREAD

**Issue by 1610200527** [sharding-sphere/sharding-sphere#1524] opened 2018-11-28 10:50 UTC
hello:
    I use sharding-jdbc 3.0.0,durid,mysql 5,spring transaction manager.
    One database,one table sharding,when i Include insert and delete in a transaction, prompting deadlocks when the transaction is called concurrently.  
   The sharding table has a primarykey,has a index width cloumn x1,delete by x1.
   The error is:
org.springframework.dao.DeadlockLoserDataAccessException: ### Error updating database. Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction### The error may involve defaultParameterMap### The error occurred while setting parameters### SQL: insert into xx (x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15,x16) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?)### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction; SQL []; Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction\tat org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:263)\tat org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)\tat org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)\tat org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)\tat com.sun.proxy.$Proxy58.insert(Unknown Source)\tat org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)\tat org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)\tat org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)\tat com.sun.proxy.$Proxy66.insertxx(Unknown Source)\tat org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)\tat org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)\tat org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)\tat org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)\tat org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)\tat 
java.lang.Thread.run(Thread.java:745)Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)\tat com.mysql.jdbc.Util.handleNewInstance(Util.java:425)\tat com.mysql.jdbc.Util.getInstance(Util.java:408)\tat com.mysql.jdbc.SQLError.createSQLException(SQLError.java:952)\tat com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)\tat com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)\tat com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)\tat com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)\tat com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)\tat com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)\tat com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)\tat com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498)\tat io.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$4.executeSQL(PreparedStatementExecutor.java:158)\tat io.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor$4.executeSQL(PreparedStatementExecutor.java:154)\tat io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute0(SQLExecuteCallback.java:85)\tat io.shardingsphere.core.executor.sql.execute.SQLExecuteCallback.execute(SQLExecuteCallback.java:69)\tat io.shardingsphere.core.executor.ShardingExecuteEngine.syncGroupExecute(ShardingExecuteEngine.java:182)\tat io.shardingsphere.core.executor.ShardingExecuteEngine.groupExecute(ShardingExecuteEngine.java:158)\tat io.shardingsphere.core.executor.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:71)\tat io.shardingsphere.core.executor.sql.execute.SQLExecuteTemplate.executeGroup(SQLExecuteTemplate.java:54)\tat io.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:122)\tat io.shardingsphere.shardingjdbc.executor.PreparedStatementExecutor.execute(PreparedStatementExecutor.java:161)\tat io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:139)\tat org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)\tat org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)\tat org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)\tat org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)\tat org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)\tat sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\tat java.lang.reflect.Method.invoke(Method.java:498)\tat org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)\tat com.sun.proxy.$Proxy94.update(Unknown Source)\tat org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)\tat org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)\tat sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\tat java.lang.reflect.Method.invoke(Method.java:498)\tat org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)\t... 30 more

**Comment by KomachiSion** [comment] 2018-11-29 02:55
Hello @1610200527. Would you mind provide your configuration, table structure, and complete SQL in the transaction? It will help us to position problem.

If you can provide example code which can recurrent this problem will be better.

**Comment by 1610200527** [comment] 2018-11-29 06:31
This is dataSourceConfig class
@Configuration
@MapperScan(basePackages = "xx.xx.xx.dao.main",sqlSessionTemplateRef = "mainSqlSessionTemplate")
public class MainDataSourceConfig {
@Autowired
    private DruidSourceConfig druidSourceConfig;

    @Bean(name = "mainTransactionManager")
    @Primary
    public DataSourceTransactionManager setTransactionManager(@Qualifier("mainDataSource") DataSource dataSource) {
        DataSourceTransactionManager dataSourceTransactionManager = new DataSourceTransactionManager(dataSource);
        return dataSourceTransactionManager;
    }

    @Bean(name = "mainSqlSessionFactory")
    public SqlSessionFactory setSqlSessionFactory(@Qualifier("mainDataSource") DataSource dataSource) throws Exception {
        SqlSessionFactoryBean bean = new SqlSessionFactoryBean();
        bean.setDataSource(dataSource);
        try{
            bean.setMapperLocations(new PathMatchingResourcePatternResolver().getResources("classpath:mybatis/mapper/main/*.xml"));
        }catch (Exception ex){
            LoggerHelper.error(this.getClass(),ex.getMessage(),ex);
        }
        return bean.getObject();
    }

    @Bean(name = "mainSqlSessionTemplate")
    public SqlSessionTemplate setSqlSessionTemplate(@Qualifier("mainSqlSessionFactory") SqlSessionFactory sqlSessionFactory) throws Exception {
        SqlSessionTemplate sqlSessionTemplate = new SqlSessionTemplate(sqlSessionFactory);
        return sqlSessionTemplate;
    }

    @Bean(name="mainDataSource")
    public DataSource buildDataSource() {
        DataSource dataSource = null;
        try{
            Map<String, DataSource> dataSourceMap = new HashMap<>(1);
            dataSourceMap.put("default", druidSourceConfig.getDruidSource());
            ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
            shardingRuleConfig.getTableRuleConfigs().add(getTempPhotoTableRuleConfiguration());
            shardingRuleConfig.setDefaultDatabaseShardingStrategyConfig(new NoneShardingStrategyConfiguration());
            Properties properties = new Properties();
            properties.setProperty("sql.show","false");
            dataSource = ShardingDataSourceFactory.createDataSource(dataSourceMap, shardingRuleConfig, new ConcurrentHashMap(), properties);

        }catch (Exception ex){
            LoggerHelper.error(MainDataSourceConfig.class, "创建数据库链接失败！", ex);
        }
        return dataSource;
    }

    TableRuleConfiguration getTempPhotoTableRuleConfiguration() {
        TableRuleConfiguration result = new TableRuleConfiguration();
        result.setLogicTable("temp_photo");
        result.setActualDataNodes("default.temp_photo_${0..9}");
        result.setTableShardingStrategyConfig(new StandardShardingStrategyConfiguration("temp_id", new ModuleTableShardingAlgorithm()));
        DefaultKeyGenerator defaultKeyGenerator = new DefaultKeyGenerator();
        defaultKeyGenerator.setWorkerId(druidSourceConfig.getWorkId());
        result.setKeyGenerator(defaultKeyGenerator);
        result.setKeyGeneratorColumnName("photo_id");
        return result;
    }
}

**Comment by 1610200527** [comment] 2018-11-29 06:35
This is create table sql,we sharding 10 tables,from 0 to 9.

DROP TABLE IF EXISTS `temp_photo_0`;
CREATE TABLE `temp_photo_0` (
  `photo_id` bigint(20) NOT NULL,
  `temp_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `temp_a` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `temp_b` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL
  PRIMARY KEY (`photo_id`),
  KEY `temp_photo_index` (`temp_id`,`temp_a`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;

**Comment by 1610200527** [comment] 2018-11-29 06:46
This is service class,include transaction infomation.

@Service
public class TempServiceImpl implements TempService {

    @Autowired
    private TempInfoMapper tempInfoMapper;

    @Autowired
    private TempPhotoMapper tempPhotoMapper;

    @Autowired
    private KafkaProducerService kafkaProducerService;

    @Value("${spring.kafka.temp.sync.topic:test-topic}")
    private String topic;

    @Transactional(rollbackFor = Exception.class)
    @Override
    public void saveInfo(TempImportData tempImportData) {
        this.tempInfoMapper.insert(tempImportData);
        this.tempPhotoMapper.insertPhotos(tempImportData.getPhotoList());
        TempInfo tempInfo = new TempInfo();
        // 发送消息到kafka
        BeanUtils.copyProperties(tempImportData, tempInfo);
        syncTempToKafka(tempInfo, tempImportData.getPhotoList());
    }

    @Transactional(rollbackFor = Exception.class)
    @Override
    public void editInfo(tempImportData tempImportData, String temp_a) {
        this.delInfo(tempImportData, temp_a);
        this.saveInfo(tempImportData);
    }

    @Transactional(rollbackFor = Exception.class)
    @Override
    public void delInfo(TmepImportData tempImportData, String temp_a) {
        this.tempInfoMapper.deleteById(tempImportData.getId(), temp_a);
        this.tempPhotoMapper.deleteById(tempImportData.getId(), temp_a);
    }

    @Override
    public void syncTempToKafka(TempInfo tempInfo, List<TempPhoto> photoList) {
        .....
    }
}

**Comment by KomachiSion** [comment] 2018-11-29 07:49
Thinks for your feedback.
We will try to reproduce the problem, if there are other relevant information, please update in the comments in time.

**Comment by KomachiSion** [comment] 2018-11-29 07:59
Would you mind provide any informations for TempInfoMapper?

**Comment by KomachiSion** [comment] 2018-11-29 09:11
Hello @1610200527.
I try to recurrent the problem without TempInfoMapper and KafkaService, but failed.

The following are my insert and delete statements and service：
```
<insert id="insertPhotos">
    INSERT INTO temp_photo (photo_id, temp_id, temp_a, temp_b) VALUES
    <foreach collection ="list" item="each" index= "index" separator =",">
        (#{each.photoId,jdbcType=BIGINT}, #{each.tempId,jdbcType=VARCHAR}, #{each.tempA,jdbcType=VARCHAR}, #{each.tempB,jdbcType=VARCHAR})
    </foreach >;
</insert>
    
<delete id="deleteById">
    DELETE FROM temp_photo WHERE temp_id = #{arg0,jdbcType=VARCHAR} AND temp_a = #{arg1,jdbcType=VARCHAR};
</delete>
```

```
@Service
public class TempServiceImpl {
    
    @Autowired
    private TempPhotoMapper tempPhotoMapper;
    
    public void init() {
        this.tempPhotoMapper.createTableIfNotExists();
    }
    
    @Transactional(rollbackFor = Exception.class)
    public void saveInfo(TempImportData tempImportData) {
        this.tempPhotoMapper.insertPhotos(tempImportData.getPhotoList());
    }
    
    @Transactional(rollbackFor = Exception.class)
    public void editInfo(TempImportData tempImportData, String temp_a) {
        this.delInfo(tempImportData, temp_a);
        this.saveInfo(tempImportData);
    }
    
    @Transactional(rollbackFor = Exception.class)
    public void delInfo(TempImportData tempImportData, String temp_a) {
        this.tempPhotoMapper.deleteById(tempImportData.getId(), temp_a);
    }
}
```

And I test insert 10 rows to table by `saveInfo ` and do edit one of by `editInfo`, it works well.
```
    private static void process(ConfigurableApplicationContext applicationContext) {
        TempServiceImpl tempService = applicationContext.getBean(TempServiceImpl.class);
        tempService.init();
        
        String tempId = "temp_test";
        TempImportData initData = new TempImportData(tempId);
        TempImportData newData = new TempImportData(tempId);
        
        for (long i = 0; i < 10; i++) {
            TempPhoto tempPhoto = new TempPhoto();
            tempPhoto.setPhotoId(i);
            tempPhoto.setTempId(tempId);
            tempPhoto.setTempA("xxx" + i);
            tempPhoto.setTempB("yyy" + i);
            initData.getPhotoList().add(tempPhoto);
        }
        TempPhoto tempPhoto = new TempPhoto();
        tempPhoto.setPhotoId(1L);
        tempPhoto.setTempId(tempId);
        tempPhoto.setTempA("aaa" + 1);
        tempPhoto.setTempB("bbb" + 1);
        newData.getPhotoList().add(tempPhoto);
        
        tempService.saveInfo(initData);
        tempService.editInfo(newData, "xxx1");
    }
```

I recommend canceling the Kafka message and trying again.
If the problem still exists, I prefer that providing more informations so that we can recurrent this problem.

**Comment by 1610200527** [comment] 2018-11-29 11:14
Thank you reply problem,Today,I canceling the Kafka message and test ,did't discover problems,i will continue test,feedback after finding problems.

**Comment by KomachiSion** [comment] 2018-11-30 11:52
Hi @1610200527.  Is there any progress on this issue?
If not more questions, can we close this issue? Thanks.

**Comment by terrymanu** [comment] 2018-12-07 14:55
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Closed by terrymanu** 2018-12-07 14:55 UTC
Labels: need feedback
