### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by helloqhx** [sharding-sphere/sharding-sphere#1419] opened 2018-11-02 14:24 UTC
I use sharding-jdbc to batch insert to mysql.
sharding key: a varchar column, e.g.`hash`
database sharding algorithm: `hash.charAt(0) % 3`
table sharding algorithm: `hash.charAt(0) % 4`

when i do batch insert with sharding-jdbc: 

> Exception in thread "Thread-1" java.lang.ArrayIndexOutOfBoundsException: 1
        at io.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor.accumulate(BatchPreparedStatementExecutor.java:176)
        at io.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor.executeBatch(BatchPreparedStatementExecutor.java:168)
        at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeBatch(ShardingPreparedStatement.java:236)
        at org.apache.commons.dbutils.QueryRunner.batch(QueryRunner.java:192)
        at org.apache.commons.dbutils.QueryRunner.batch(QueryRunner.java:151)

**Comment by terrymanu** [comment] 2018-11-03 09:34
Could you provide more details follow the template?

Template:

## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [Sharding-Sphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Sphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by terrymanu** [comment] 2018-11-08 15:39
Hi, any update on this issue? we will close this issue after 2 days if no more response.

**Comment by terrymanu** [comment] 2018-11-13 14:07
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

**Closed by terrymanu** 2018-11-13 14:07 UTC
Labels: need feedback

**Comment by guid-git** [comment] 2020-12-16 07:54
> I use sharding-jdbc to batch insert to mysql.
> sharding key: a varchar column, e.g.`hash`
> database sharding algorithm: `hash.charAt(0) % 3`
> table sharding algorithm: `hash.charAt(0) % 4`
> 
> when i do batch insert with sharding-jdbc:
> 
> > Exception in thread "Thread-1" java.lang.ArrayIndexOutOfBoundsException: 1
> > at io.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor.accumulate(BatchPreparedStatementExecutor.java:176)
> > at io.shardingsphere.shardingjdbc.executor.BatchPreparedStatementExecutor.executeBatch(BatchPreparedStatementExecutor.java:168)
> > at io.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingPreparedStatement.executeBatch(ShardingPreparedStatement.java:236)
> > at org.apache.commons.dbutils.QueryRunner.batch(QueryRunner.java:192)
> > at org.apache.commons.dbutils.QueryRunner.batch(QueryRunner.java:151)

have you slove this problem?
