### ISSUE TITLE
use master-slave and r/w split mode，when distributed deploy mult-apps, the database connections massive increase.

### ISSUE THREAD

**Issue by olderzhou** [sharding-sphere/sharding-sphere#934] opened 2018-06-14 13:29 UTC
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
3.0.0.M1
### Expected behavior （您预期的结果是）
连接数等比例增加
### Actual behavior （实际运行的结果是）
数据莫名其妙增加了很多连接
### Steps to reproduce the behavior （可重现问题的操作步骤）

https://github.com/olderzhou/netty-test.git

在windows里面复现

下载好代码，进入  run-local.sh所在目录，分别执行

./run-lcoal local
./run-lcoal local2
./run-lcoal local3

查看数据库连接数  show processlist

![Uploading 企业微信截图_20180614212716.png…]()

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

**Comment by terrymanu** [comment] 2018-06-15 03:07
Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

**Comment by terrymanu** [comment] 2018-06-15 03:11
i saw your example, where do you use sharding-sphere? in your pom, i cannot find any place to import sharding-sphere

**Comment by olderzhou** [comment] 2018-06-15 03:42
@terrymanu sharding-sphere base on the parent pom ,
here i use 
<dependency>
			<groupId>io.shardingsphere</groupId>
			<artifactId>sharding-jdbc-orchestration-spring-boot-starter</artifactId>
			<version>${sharding-sphere.version}</version>
		</dependency>

**Comment by olderzhou** [comment] 2018-06-15 03:44
我这边测试的结果集，
run-local   连接数9
run-local2 连接数26
run-local3 练技术54

多次运行，连接数还会动态变，但是属于同一个数据量级

**Comment by tuohai666** [comment] 2018-08-13 08:01
Hi @olderzhou , I'm sorry that I can't get your point.
The most important things:
What you expect? Input A, and the output is B, C, D.
What the actual output? Input A, and the output is E, F, G.
Could you provide imformation like that?

In your example, you configured 6 connection pool in one database, and each pool size is 30.
Did the connections amount ever over 30 * 6 = 240?

**Comment by olderzhou** [comment] 2018-08-13 08:12
实际是这样的，最小链接数是1，
运行第一个实例，run-local ， 查看连接数是9

运行第二个实例，run-local2 ，查看连接数26【此时实例1与实例2同时运行】

运行第三个实例，run-local3 ，查看连接数54【此时实例1,2,3同时运行】

你可以下载代码复现，这个问题是100%复现的

**Comment by tuohai666** [comment] 2018-08-13 08:47
If you don't want to use English, could your join SS wechat group? We can talk there.

**Comment by tuohai666** [comment] 2018-08-13 09:05
Please answer my question above first.
Also, I can't find  run-local.sh.

**Comment by olderzhou** [comment] 2018-08-13 09:17
@tuohai666 
现在的问题是，当我分布式运行多个实例的时候，数据源连接数会暴增。
假设我配置的连接词是一主俩从，我示例中需要链接的俩个库，那么对应的连接数，当运行一个实例时应该是6，运行俩个实例是时候应该是12，三个则是18，实际情况是连接数会远多于这个。

https://github.com/olderzhou/netty-test/blob/master/run.sh
这是你说的找不到的脚本

./run.sh  local
./run.sh local1
./run.sh local2
你可以这样运行，运行前你需要看一下里面的内容，路径配置可能跟你本地环境不太一致

**Comment by tuohai666** [comment] 2018-08-13 09:54
我明白你的意思了，能加入SS微信群吗？还有些细节想问你，在群里方便些

**Comment by olderzhou** [comment] 2018-08-13 10:05
@tuohai666 申请啦，klaus，需要同意下

**Comment by tuohai666** [comment] 2018-08-13 12:54
@olderzhou, thanks for your effort to findout this bug.
The config **overwrite: true** of zookeeper cause a wrong number of connection pool.

**Comment by tristaZero** [comment] 2018-08-15 08:29
@olderzhou 
Hi, sir. After we analyze your problem, we decide to fix this problem and give an enhancement for Sharding Orchestration. 
The reason of a boom of connection is as follows:
* The new datasources will be created using the minIdle configuration of datasources in registry when new instance is online.
* The old datasources are not be closed when configuration in registry is updated.

Please refer to the issue #1150 , #1151 to solve this issue.
Any problems, please contact us.

P.S. Can you edit the title of this issue in English? Thanks.

**Comment by tuohai666** [comment] 2018-08-21 11:38
Resolved. 
Refer to #1150.

**Closed by tuohai666** 2018-08-21 11:38 UTC
Labels: bug
