### ISSUE TITLE
updating database  java.lang.NullPointerException

### ISSUE THREAD

**Issue by selrain** [sharding-sphere/sharding-sphere#1098] opened 2018-08-05 04:37 UTC
version：3.0.0.M1
i  am not use sharding it  perform normal，but sharding have problem，like this：
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.NullPointerException
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 35 more
Caused by: java.lang.NullPointerException
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:311)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:563)
	at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:750)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1122)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1118)
	at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:104)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:338)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy86.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 41 more

my config file：
sharding.jdbc.datasource.names=ds_0,ds_1

sharding.jdbc.datasource.ds_0.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds_0.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds_0.url=jdbc:mysql://127.0.0.1:3306/ds0
sharding.jdbc.datasource.ds_0.username=root
sharding.jdbc.datasource.ds_0.password=ymyselrain

sharding.jdbc.datasource.ds_1.type=com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.ds_1.driver-class-name=com.mysql.jdbc.Driver
sharding.jdbc.datasource.ds_1.url=jdbc:mysql://127.0.0.1:3306/ds1
sharding.jdbc.datasource.ds_1.username=root
sharding.jdbc.datasource.ds_1.password=ymyselrain

sharding.jdbc.config.sharding.default-database-strategy.inline.sharding-column=pid
sharding.jdbc.config.sharding.default-database-strategy.inline.algorithm-expression=ds$->{pid % 2}

sharding.jdbc.config.sharding.tables.t_activity.actual-data-nodes=ds$->{0..1}.t_activity_$->{0..3}
sharding.jdbc.config.sharding.tables.t_activity.table-strategy.inline.sharding-column=pid
sharding.jdbc.config.sharding.tables.t_activity.table-strategy.inline.algorithm-expression=t_activity_$->{pid % 4}
sharding.jdbc.config.sharding.tables.t_activity.key-generator-column-name=pid

**Comment by terrymanu** [comment] 2018-08-05 06:01
the root cause of exception is come from druid. It seems not cause by sharding-sphere, please check it again. I just close it.

If you still think this exception is caused by sharding-sphere anyway, please follow issue template, to provide all information we need.

**Closed by terrymanu** 2018-08-05 06:01 UTC
