### ISSUE TITLE
When using join, the SQL is sent to all dataNode

### ISSUE THREAD

**Issue by fanyaoxuan** [sharding-sphere/sharding-sphere#1606] opened 2018-12-12 10:39 UTC
## Question
When using join, the SQL is sent to all dataNode:

my_sql: 
![image](https://user-images.githubusercontent.com/22194156/49864319-332f5400-fe3d-11e8-8837-0d38435d0be7.png)

sent to all dataNode:
![image](https://user-images.githubusercontent.com/22194156/49864339-3f1b1600-fe3d-11e8-97df-2c3fb8abc0ae.png)

**Comment by terrymanu** [comment] 2018-12-12 15:31
What is your sharding rule?

**Comment by fanyaoxuan** [comment] 2018-12-13 00:50
oh，I forgot this
sharding rule: 
  sharding colum： calendar 
implement RangeShardingAlgorithm:  by month 

 6 databases:  sharding0  ... sharding5
Each database is divided into two months of data:  sharding0.table6   sharding0:table12
                                                                                  sharding1.table1   sharding1:table7

**Comment by fanyaoxuan** [comment] 2018-12-13 08:21
> What is your sharding rule?

oh，I forgot this
sharding rule:
sharding table: t_equip_online_time
sharding colum： calendar
implement RangeShardingAlgorithm: by month

6 databases: sharding0 ... sharding5
Each database is divided into two months of data: sharding0.table6 sharding0:table12
sharding1.table1 sharding1:table7

**Comment by KomachiSion** [comment] 2018-12-14 01:20
@fanyaoxuan, your sharding rule looks like only shard **t_equip_online_time** table. How about **monitor** and **monitor_type**? Are they broadcast table?

**Comment by KomachiSion** [comment] 2018-12-14 07:43
Hi @fanyaoxuan. This problem should be caused by `date` method in your where clause. ShardingSphere can route number, plain text and SQL placeholder in where clause. When using mysql method like `date`, ShardingSphere will do full routing for this SQL.

I test the SQL
```
SELECT * FROM t_equip_online_time WHERE calendar BETWEEN #{arg0, jdbcType=DATE} AND #{arg1, jdbcType=DATE}
```
it work well.
```
[INFO ] 2018-12-14 15:30:02,312 --main-- [Sharding-Sphere-SQL] Logic SQL: SELECT * FROM t_equip_online_time WHERE calendar BETWEEN ? AND ? 
[INFO ] 2018-12-14 15:30:02,312 --main-- [Sharding-Sphere-SQL] SQLStatement: SelectStatement(super=DQLStatement(super=io.shardingsphere.core.parsing.parser.sql.dql.select.SelectStatement@5341641d), containStar=true, selectListLastPosition=9, groupByLastPosition=0, items=[StarSelectItem(owner=Optional.absent())], groupByItems=[], orderByItems=[], limit=null, subQueryStatement=null, subQueryStatements=[]) 
[INFO ] 2018-12-14 15:30:02,312 --main-- [Sharding-Sphere-SQL] Actual SQL: sharding0 ::: SELECT * FROM t_equip_online_time12 WHERE calendar BETWEEN ? AND ? ::: [[2018-10-14, 2018-12-14]] 
[INFO ] 2018-12-14 15:30:02,312 --main-- [Sharding-Sphere-SQL] Actual SQL: sharding4 ::: SELECT * FROM t_equip_online_time10 WHERE calendar BETWEEN ? AND ? ::: [[2018-10-14, 2018-12-14]] 
[INFO ] 2018-12-14 15:30:02,312 --main-- [Sharding-Sphere-SQL] Actual SQL: sharding5 ::: SELECT * FROM t_equip_online_time11 WHERE calendar BETWEEN ? AND ? ::: [[2018-10-14, 2018-12-14]] 
```

So, I suggest you remove `date` method in your SQL, and try again.

**Comment by fanyaoxuan** [comment] 2018-12-14 07:48
> should

sorry,I discovered the problem yesterday.
If I use the date function, the sharding rule will fail.

**Comment by KomachiSion** [comment] 2018-12-14 08:08
> > should
> 
> sorry,I discovered the problem yesterday.
> If I use the date function, the sharding rule will fail.

All right, if you don't have any more question, we will close this issue.
Thanks for your feedback.

**Comment by fanyaoxuan** [comment] 2018-12-14 08:12
I want to give you more details later.For reference.

**Closed** 2018-12-14 11:36 UTC
Labels: investigate
