### ISSUE TITLE
error when Logic table have the same name as Actual table .

### ISSUE THREAD

**Issue by quaider** [sharding-sphere/sharding-sphere#1715] opened 2019-01-04 16:48 UTC
### update
it looks like a driver compatibility problem with `mysql-connector-java` of 6.0.6 or above
the issue title should updated in some days
---
i just use database sharding not table sharding, but when Logic table have the same name as Actual table, some error occurs
``` 
Caused by: java.sql.SQLException: Column name pattern can not be NULL or empty.
```
here is my config of yaml
```yaml
shardingRule:
  tables:
   # same name as Actual table， but when i use ms_ds${1..2}.t_user1, it will be ok
   # but when i change table name in mysql to t_user1，then ms_ds${1..2}.t_user1 does not work either
    t_user:
      actualDataNodes: ms_ds${1..2}.t_user
      databaseStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: ms_ds${id % 2 + 1}

      keyGeneratorColumnName: id
```

i think it may be a bug

**Comment by terrymanu** [comment] 2019-01-04 17:34
Can you fill some necessary information with template below?

**Comment by terrymanu** [comment] 2019-01-04 17:34
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
- Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

### Expected behavior

### Actual behavior

### Reason analyze (If you can)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

### Example codes for reproduce this issue (such as a github link).

**Comment by quaider** [comment] 2019-01-04 17:38
@terrymanu 
all my config, my  version is `3.1.0`
```yaml
dataSources:
  ds1: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.129:13306/shop
    username: root
    password: root

  ds1_sl1: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.129:13307/shop
    username: root
    password: root

  ds1_sl2: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.129:13308/shop
    username: root
    password: root

  ds2: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.129:13406/shop
    username: root
    password: root

  ds2_sl1: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.129:13407/shop
    username: root
    password: root

  ds2_sl2: !!com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.8.129:13408/shop
    username: root
    password: root

shardingRule:
  tables:
    t_order:
      actualDataNodes: ms_ds${1..2}.t_order${1..3}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: t_order${id % 3 + 1}

      databaseStrategy:
        inline:
          shardingColumn: buyer_id
          algorithmExpression: ms_ds${buyer_id % 2 + 1}

      keyGeneratorColumnName: id

  defaultKeyGeneratorClassName: io.shardingsphere.core.keygen.DefaultKeyGenerator

  masterSlaveRules:
    ms_ds1:
      masterDataSourceName: ds1
      slaveDataSourceNames:
        - ds1_sl1
        - ds1_sl2
      loadBalanceAlgorithmType: ROUND_ROBIN

    ms_ds2:
      masterDataSourceName: ds2
      slaveDataSourceNames:
        - ds2_sl1
        - ds2_sl2
      loadBalanceAlgorithmType: ROUND_ROBIN

#props:
#  sql.show: true
```
mysql is 
![image](https://user-images.githubusercontent.com/12459496/50701969-66ef4980-108a-11e9-9330-982c32114e11.png)

and i got the same error
```
Caused by: java.sql.SQLException: Column name pattern can not be NULL or empty.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545) ~[mysql-connector-java-6.0.6.jar:6.0.6]
```

**Comment by quaider** [comment] 2019-01-04 17:47
> ## Bug Report
> **For English only**, other languages will not accept.
> 
> Before report a bug, make sure you have:
> 
> * Searched open and closed [GitHub issues](https://github.com/sharding-sphere/sharding-sphere/issues).
> * Read documentation: [ShardingSphere Doc](http://shardingsphere.io/document/current/en/overview/).
> 
> Please pay attention on issues you submitted, because we maybe need more details.
> If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.
> 
> Please answer these questions before submitting your issue. Thanks!
> 
> ### Which version of ShardingSphere did you use?
3.1.0
> ### Which project did you use? Sharding-JDBC or Sharding-Proxy?
 Sharding-JDBC
> ### Expected behavior
run without exception
> ### Actual behavior
Caused by: java.sql.SQLException: Column name pattern can not be NULL or empty.
> ### Reason analyze (If you can)
 if the table in mysql has the same name as actualDataNodes it happens, i dont kown why
> ### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
plz see below
> ### Example codes for reproduce this issue (such as a github link).
plz see below

**Comment by quaider** [comment] 2019-01-04 18:09
i have found this may cause the error in `TableMetaDataLoader.java`，the `columnNamePattern` arg is hardcode to null as below
`connection.getMetaData().getColumns(catalog, null, actualTableName, null)`
```java
private List<ColumnMetaData> getColumnMetaDataList(final Connection connection, final String catalog, final String actualTableName) throws SQLException {
        List<ColumnMetaData> result = new LinkedList<>();
        Collection<String> primaryKeys = getPrimaryKeys(connection, catalog, actualTableName);
        try (ResultSet resultSet = connection.getMetaData().getColumns(catalog, null, actualTableName, null)) {
            while (resultSet.next()) {
                String columnName = resultSet.getString("COLUMN_NAME");
                String columnType = resultSet.getString("TYPE_NAME");
                result.add(new ColumnMetaData(columnName, columnType, primaryKeys.contains(columnName)));
            }
        }
        return result;
    }
```

**Comment by quaider** [comment] 2019-01-04 18:17
em,-:(，i use a low version of `mysql-connector-java`, then everything is ok!

**Comment by quaider** [comment] 2019-01-07 01:50
> > em,-:(，i use a low version of `mysql-connector-java`, then everything is ok!
> 
> Please explicitly point out which version of `mysql-connector-java` can not work and which version of `mysql-connector-java` can work.

`mysql`: 5.7
`mysql-connector-java`: 6.0.6 (can not work)，5.1.47 (works)

**Comment by tuohai666** [comment] 2019-01-07 04:37
@quaider I can't reproduce. What is the SQL please?

**Comment by tuohai666** [comment] 2019-01-07 04:43
@quaider Can you try the 3.1.0 version just released today(2019-1-7)?

**Comment by tuohai666** [comment] 2019-01-07 04:52
@quaider Also please check your project, is it run well with jdbc-6.0.6 without Sharding-JDBC?

**Comment by quaider** [comment] 2019-01-07 13:58
@tuohai666  i have try it just now
here is my package config in current test
```xml
<dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>6.0.6</version>
      </dependency>
      <dependency>
        <groupId>io.shardingsphere</groupId>
        <artifactId>sharding-jdbc-core</artifactId>
        <version>3.1.0</version>
      </dependency>
```

when use  `sharding-jdbc-core`, error occurs when application start
when just use druid everything works well,

so, it seems to have nothing to do with what my  SQL is, because excepton throw at startup time with  `sharding-jdbc-core`

if you want more details， you can get code here https://github.com/quaider/nanoservice

and my database file below（.sql file can't upload, so i use a .log file instead）

[shop.log](https://github.com/sharding-sphere/sharding-sphere/files/2732972/shop.log)

hope you fix it if it is a bug

**Comment by tuohai666** [comment] 2019-01-09 09:03
@quaider Would you mind use HikariCP instead of Druid to have a try? Meanwhile I'll try Druid in my environment.

**Comment by tuohai666** [comment] 2019-01-09 09:45
@quaider Please tell your Druid version.

**Comment by tuohai666** [comment] 2019-01-09 09:53
url: jdbc:mysql://192.168.8.129:13306/shop
    url: jdbc:mysql://192.168.8.129:13307/shop
    url: jdbc:mysql://192.168.8.129:13308/shop
    url: jdbc:mysql://192.168.8.129:13406/shop
    url: jdbc:mysql://192.168.8.129:13407/shop
    url: jdbc:mysql://192.168.8.129:13408/shop

@quaider I think your have 6 mysql instance on one machine, am I right?

**Comment by tuohai666** [comment] 2019-01-09 09:58
@quaider Please provide the full log with Exceptions.

**Comment by quaider** [comment] 2019-01-09 12:20
good job, how can i try it?

**Comment by tuohai666** [comment] 2019-01-09 13:00
Lucky guy, you don't need to answer all my questions after I resolve this problem. You can't try until https://github.com/sharding-sphere/sharding-sphere/pull/1727 be merged. You may try dev branch tomorrow.
The root cause of this issue is actually Connector/j 6.x checked columnNamePattern in getColumns.
The reason why I can't reproduce it is I use MySQL 5.6 at first. Finally, I turn to MySQL 5.7, and the Exception burst.

**Closed** 2019-01-09 15:12 UTC
Labels: investigate
